version: '3.8'

services:
  fnrefresher:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - "/opt/ftp/files:/opt/app/files"
    environment:
      - JSONPATH=/opt/app/files
      - BDPATH=/opt/app/files
      - SDKEY='23a910df-77e0-4417-a23e-3617b6a0f0ef'

  ftpserver:
    image: stilliard/pure-ftpd
    container_name: ftpserver
    ports:
      - "21:21"
      - "30000-30005:30000-30005"
    volumes:
      - "/opt/ftp/files:/home/ftpuser"
# uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
#      - "/etc/letsencrypt/live/<your_server>/cert.pem:/etc/ssl/private/pure-ftpd-cert.pem"
#      - "/etc/letsencrypt/live/<your_server>/privkey.pem:/etc/ssl/private/pure-ftpd-key.pem"
    environment:
#     PUBLICHOST:
      FTP_USER_NAME: ftpuser
      FTP_USER_PASS: 11
      FTP_USER_HOME: /home/ftpuser
# for ssl/tls
#     ADDED_FLAGS: '--tls=2'
    restart: always
    depends_on:
      - fnrefresher